import { Peca, Venda } from "./types";

function daysAgo(n: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 30, 0, 0);
  return d.toISOString();
}

export const initialPecas: Peca[] = [
  {
    id: "p1",
    sku: "FLT-001",
    nome: "Filtro de Óleo",
    categoria: "Filtros",
    marca: "Tecfil",
    precoCusto: 12.5,
    precoVenda: 24.9,
    quantidade: 42,
    estoqueMinimo: 10,
    localizacao: "A1-01",
  },
  {
    id: "p2",
    sku: "FLT-002",
    nome: "Filtro de Ar",
    categoria: "Filtros",
    marca: "Mann Filter",
    precoCusto: 18.0,
    precoVenda: 39.9,
    quantidade: 6,
    estoqueMinimo: 8,
    localizacao: "A1-02",
  },
  {
    id: "p3",
    sku: "FLT-003",
    nome: "Filtro de Combustível",
    categoria: "Filtros",
    marca: "Tecfil",
    precoCusto: 15.0,
    precoVenda: 32.5,
    quantidade: 15,
    estoqueMinimo: 10,
    localizacao: "A1-03",
  },
  {
    id: "p4",
    sku: "FRE-001",
    nome: "Pastilha de Freio Dianteira",
    categoria: "Freios",
    marca: "Fras-le",
    precoCusto: 45.0,
    precoVenda: 89.9,
    quantidade: 20,
    estoqueMinimo: 6,
    localizacao: "B2-01",
  },
  {
    id: "p5",
    sku: "FRE-002",
    nome: "Disco de Freio Traseiro",
    categoria: "Freios",
    marca: "Fremax",
    precoCusto: 70.0,
    precoVenda: 149.9,
    quantidade: 3,
    estoqueMinimo: 4,
    localizacao: "B2-02",
  },
  {
    id: "p6",
    sku: "FRE-003",
    nome: "Fluido de Freio DOT4",
    categoria: "Óleos e Fluidos",
    marca: "Bosch",
    precoCusto: 14.0,
    precoVenda: 28.9,
    quantidade: 25,
    estoqueMinimo: 8,
    localizacao: "C1-01",
  },
  {
    id: "p7",
    sku: "SUS-001",
    nome: "Amortecedor Dianteiro",
    categoria: "Suspensão",
    marca: "Cofap",
    precoCusto: 120.0,
    precoVenda: 249.9,
    quantidade: 8,
    estoqueMinimo: 4,
    localizacao: "D1-01",
  },
  {
    id: "p8",
    sku: "SUS-002",
    nome: "Kit Amortecedor Traseiro",
    categoria: "Suspensão",
    marca: "Monroe",
    precoCusto: 135.0,
    precoVenda: 279.9,
    quantidade: 2,
    estoqueMinimo: 4,
    localizacao: "D1-02",
  },
  {
    id: "p9",
    sku: "SUS-003",
    nome: "Bieleta de Suspensão",
    categoria: "Suspensão",
    marca: "Nakata",
    precoCusto: 18.0,
    precoVenda: 39.9,
    quantidade: 30,
    estoqueMinimo: 10,
    localizacao: "D1-03",
  },
  {
    id: "p10",
    sku: "ELE-001",
    nome: "Bateria 60Ah",
    categoria: "Elétrica",
    marca: "Moura",
    precoCusto: 280.0,
    precoVenda: 449.9,
    quantidade: 10,
    estoqueMinimo: 3,
    localizacao: "E1-01",
  },
  {
    id: "p11",
    sku: "ELE-002",
    nome: "Vela de Ignição",
    categoria: "Elétrica",
    marca: "NGK",
    precoCusto: 8.0,
    precoVenda: 18.9,
    quantidade: 60,
    estoqueMinimo: 20,
    localizacao: "E1-02",
  },
  {
    id: "p12",
    sku: "ELE-003",
    nome: "Alternador",
    categoria: "Elétrica",
    marca: "Bosch",
    precoCusto: 350.0,
    precoVenda: 620.0,
    quantidade: 1,
    estoqueMinimo: 2,
    localizacao: "E1-03",
  },
  {
    id: "p13",
    sku: "MOT-001",
    nome: "Correia Dentada",
    categoria: "Motor",
    marca: "Gates",
    precoCusto: 40.0,
    precoVenda: 89.9,
    quantidade: 14,
    estoqueMinimo: 5,
    localizacao: "F1-01",
  },
  {
    id: "p14",
    sku: "MOT-002",
    nome: "Kit Junta do Motor",
    categoria: "Motor",
    marca: "Sabó",
    precoCusto: 95.0,
    precoVenda: 189.9,
    quantidade: 5,
    estoqueMinimo: 3,
    localizacao: "F1-02",
  },
  {
    id: "p15",
    sku: "OLE-001",
    nome: "Óleo Motor 5W30 Sintético (1L)",
    categoria: "Óleos e Fluidos",
    marca: "Mobil",
    precoCusto: 28.0,
    precoVenda: 54.9,
    quantidade: 48,
    estoqueMinimo: 15,
    localizacao: "C1-02",
  },
  {
    id: "p16",
    sku: "ARR-001",
    nome: "Radiador",
    categoria: "Arrefecimento",
    marca: "Valeo",
    precoCusto: 210.0,
    precoVenda: 399.9,
    quantidade: 4,
    estoqueMinimo: 3,
    localizacao: "G1-01",
  },
  {
    id: "p17",
    sku: "ARR-002",
    nome: "Válvula Termostática",
    categoria: "Arrefecimento",
    marca: "Wahler",
    precoCusto: 25.0,
    precoVenda: 54.9,
    quantidade: 9,
    estoqueMinimo: 5,
    localizacao: "G1-02",
  },
  {
    id: "p18",
    sku: "TRA-001",
    nome: "Óleo de Câmbio ATF",
    categoria: "Transmissão",
    marca: "Castrol",
    precoCusto: 32.0,
    precoVenda: 64.9,
    quantidade: 7,
    estoqueMinimo: 8,
    localizacao: "C1-03",
  },
];

export const initialVendas: Venda[] = [
  {
    id: "v1",
    data: daysAgo(0, 9),
    itens: [
      { pecaId: "p1", nomePeca: "Filtro de Óleo", quantidade: 2, precoUnitario: 24.9 },
      { pecaId: "p15", nomePeca: "Óleo Motor 5W30 Sintético (1L)", quantidade: 4, precoUnitario: 54.9 },
    ],
    total: 2 * 24.9 + 4 * 54.9,
    formaPagamento: "Cartão",
  },
  {
    id: "v2",
    data: daysAgo(0, 14),
    itens: [
      { pecaId: "p4", nomePeca: "Pastilha de Freio Dianteira", quantidade: 1, precoUnitario: 89.9 },
    ],
    total: 89.9,
    formaPagamento: "Pix",
  },
  {
    id: "v3",
    data: daysAgo(3, 11),
    itens: [
      { pecaId: "p11", nomePeca: "Vela de Ignição", quantidade: 4, precoUnitario: 18.9 },
      { pecaId: "p13", nomePeca: "Correia Dentada", quantidade: 1, precoUnitario: 89.9 },
    ],
    total: 4 * 18.9 + 89.9,
    formaPagamento: "Dinheiro",
  },
  {
    id: "v4",
    data: daysAgo(9, 16),
    itens: [
      { pecaId: "p10", nomePeca: "Bateria 60Ah", quantidade: 1, precoUnitario: 449.9 },
    ],
    total: 449.9,
    formaPagamento: "Cartão",
  },
  {
    id: "v5",
    data: daysAgo(40, 10),
    itens: [
      { pecaId: "p7", nomePeca: "Amortecedor Dianteiro", quantidade: 2, precoUnitario: 249.9 },
    ],
    total: 2 * 249.9,
    formaPagamento: "Pix",
  },
];
